import Head from "next/head";
import Link from "next/link";
import { trpc } from "../../utils/trpc";

export default function Leaderboards() {
  const { data } = trpc.users.getAll.useQuery();
  return (
    <>
      <Head>
        <title>Alpha Gang&Games</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="p-2">
        <Link href="/">
          <a className="text-sm text-slate-300">&larr; Retour</a>
        </Link>
      </div>
      <main className="container mx-auto flex min-h-screen flex-col items-center justify-start p-4 pt-16">
        <h1 className="mb-8 text-4xl text-slate-50">Classement</h1>

        {data && data.length ? (
          <div className="flex w-1/3 flex-col justify-between">
            <div className="flex flex-grow justify-between border-b border-slate-200 py-2">
              <div className="w-20">Nom</div>
              <div>Worldle</div>
              <div>Sutom</div>
            </div>
            {data.map((user) => (
              <div
                key={user.id}
                className="flex flex-grow justify-between border-b border-slate-200 py-2"
              >
                <div className="w-20">{user.name}</div>
                <div>{user.worldleScore}</div>
                <div>{user.sutomScore}</div>
              </div>
            ))}
          </div>
        ) : null}
      </main>
    </>
  );
}
