import Head from "next/head";
import { Layout } from "../../components/Layout";
import { trpc } from "../../utils/trpc";

export default function Leaderboards() {
  const { data } = trpc.users.getAll.useQuery();
  return (
    <>
      <Head>
        <title>Alpha Gang&Games</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        {data && data.length ? (
          <table className="w-full border-collapse bg-slate-800">
            <thead>
              <tr>
                <th className="w-1/5 border-b  border-slate-600 p-4 text-left text-sm font-semibold text-slate-200">
                  Nom
                </th>
                <th className="w-1/5 border-b border-slate-600 p-4 text-center text-sm font-semibold text-slate-200">
                  # Worldle
                </th>
                <th className="w-1/5 border-b border-slate-600 p-4 text-center text-sm font-semibold text-slate-200">
                  ~ Worldle
                </th>
                <th className="w-1/5 border-b border-slate-600 p-4 text-center text-sm font-semibold text-slate-200">
                  # Sutom
                </th>
                <th className="w-1/5 border-b border-slate-600 p-4 text-center text-sm font-semibold text-slate-200">
                  ~ Sutom
                </th>
              </tr>
            </thead>
            <tbody>
              {data.map((user) => (
                <tr
                  key={user.id}
                  className="odd:bg-slate-800 even:bg-slate-700 group-hover:bg-slate-600"
                >
                  <td className="p-4 text-slate-300">{user.name}</td>
                  <td className="p-4 text-center text-slate-400">
                    {user._count.worldle}
                  </td>
                  <td className="p-4 text-center text-slate-400">
                    {user.worldleScore}
                  </td>
                  <td className="p-4 text-center text-slate-400">
                    {user._count.sutom}
                  </td>
                  <td className="p-4 text-center text-slate-400">
                    {user.sutomScore}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        ) : (
          <p>Aucune donnée</p>
        )}
      </Layout>
    </>
  );
}
