import React, { Fragment, useState } from "react";
import Link from "next/link";
import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import { Dialog, Transition } from "@headlessui/react";
import { GameChoice } from "../components/GameChoice";
import { PlayerChoice } from "../components/PlayerChoice";
import { SelectScore } from "../components/SelectScore";
import { Layout } from "../components/Layout";

const Home: NextPage = () => {
  // Form state
  const [game, setGame] = useState<string | undefined>();
  const [userId, setUserId] = useState<string | undefined>();
  const [score, setScore] = useState<number | undefined>();
  // Dialog state
  const [isDialogOpen, setIsDialogOpen] = useState(false);

  // Fetch data fns
  const { data } = trpc.users.getAll.useQuery();
  const createWorldleScoreMutation = trpc.worldle.createScore.useMutation();
  const createSutomScoreMutation = trpc.sutom.createScore.useMutation();

  // Handlers
  const handleSelectScore = (e: React.ChangeEvent<HTMLInputElement>) => {
    setScore(parseInt(e.target.value, 10));
  };

  console.log(!userId && !score && !game);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    // TODO: refacto back & front -> use a single endpoint if possible
    if (game === "worldle" && userId && score) {
      createWorldleScoreMutation.mutate(
        { userId, score },
        {
          onSuccess: () => setIsDialogOpen(true),
          onError: (error) => {
            console.error(JSON.stringify(error.message));
          },
        }
      );
    } else if (game === "sutom" && userId && score) {
      createSutomScoreMutation.mutate(
        { userId, score },
        {
          onSuccess: () => setIsDialogOpen(true),
          onError: (error) => {
            console.error(JSON.stringify(error.message));
          },
        }
      );
    }
  };

  const handleCloseDialog = () => {
    setIsDialogOpen(false);
    resetForm();
  };

  // Utils
  const resetForm = () => {
    setGame("worldle");
    setUserId("");
    setScore(4);
  };

  const getBaseUrl = () => {
    if (typeof window !== "undefined") return ""; // browser should use relative url
    if (process.env.VERCEL_URL) return `https://${process.env.VERCEL_URL}`; // SSR should use vercel url
    return `http://localhost:${process.env.PORT ?? 3000}`; // dev SSR should use localhost
  };

  return (
    <>
      <Head>
        <title>Alpha Gang&Games</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <h2 className="text-center text-xl text-slate-500">
          Hey mais salut ! tu joues à quoi ?
        </h2>
        <GameChoice game={game} onGameChoice={setGame} />
        <h2 className="text-center text-xl text-slate-500">
          ...et ton petit nom ?...
        </h2>
        <PlayerChoice
          userList={data}
          userId={userId}
          onPlayerChoice={setUserId}
        />
        <h2 className="text-center text-xl text-slate-500">
          ...balance ton score !
        </h2>
        <div className="flex justify-around">
          <SelectScore score={score} handleSelectScore={handleSelectScore} />
        </div>
        <div className="flex justify-center">
          <button
            onClick={handleSubmit}
            type="button"
            disabled={!(!!userId && !!score && !!game)}
            className="rounded bg-slate-600 px-4 py-2 hover:bg-slate-50 hover:text-slate-700 disabled:bg-slate-900 disabled:text-slate-700"
          >
            Et ça part!
          </button>
        </div>
      </Layout>
      <>
        <Transition appear show={isDialogOpen} as={Fragment}>
          <Dialog
            as="div"
            className="relative z-10"
            onClose={() => setIsDialogOpen(false)}
          >
            <Transition.Child
              as={Fragment}
              enter="ease-out duration-300"
              enterFrom="opacity-0"
              enterTo="opacity-100"
              leave="ease-in duration-200"
              leaveFrom="opacity-100"
              leaveTo="opacity-0"
            >
              <div className="fixed inset-0 bg-black bg-opacity-25" />
            </Transition.Child>

            <div className="fixed inset-0 overflow-y-auto">
              <div className="flex min-h-full items-center justify-center p-4 text-center">
                <Transition.Child
                  as={Fragment}
                  enter="ease-out duration-300"
                  enterFrom="opacity-0 scale-95"
                  enterTo="opacity-100 scale-100"
                  leave="ease-in duration-200"
                  leaveFrom="opacity-100 scale-100"
                  leaveTo="opacity-0 scale-95"
                >
                  <Dialog.Panel className="w-full max-w-md transform overflow-hidden rounded-2xl bg-white p-6 text-left align-middle shadow-xl transition-all">
                    <Dialog.Title
                      as="h3"
                      className="text-lg font-medium leading-6 text-gray-900"
                    >
                      C&apos;est dans la boîte!
                    </Dialog.Title>
                    <div className="mt-2">
                      <p className="text-sm text-gray-500">
                        Tu veux voir ton score ?
                      </p>
                    </div>

                    <div className="mt-4 flex justify-between">
                      <Link href={`${getBaseUrl()}/user/${userId}`}>
                        <button
                          type="button"
                          className="inline-flex justify-center rounded-md border border-transparent bg-orange-100 px-4 py-2 text-sm font-medium text-orange-600 hover:bg-orange-200 focus:outline-none focus-visible:ring-2 focus-visible:ring-orange-500 focus-visible:ring-offset-2"
                        >
                          Oui, steuplé!
                        </button>
                      </Link>
                      <button
                        type="button"
                        className="inline-flex justify-center rounded-md border border-transparent bg-blue-100 px-4 py-2 text-sm font-medium text-blue-900 hover:bg-blue-200 focus:outline-none focus-visible:ring-2 focus-visible:ring-blue-500 focus-visible:ring-offset-2"
                        onClick={handleCloseDialog}
                      >
                        Nan, j&apos;m&apos;en branle.
                      </button>
                    </div>
                  </Dialog.Panel>
                </Transition.Child>
              </div>
            </div>
          </Dialog>
        </Transition>
      </>
    </>
  );
};

export default Home;
